[package]
name = "is-semantic-release-configured"
version = "1.1.3"
edition = "2021"
authors = ["Eric Crosson <eric.s.crosson@utexas.edu>"]
license = "MIT OR Apache-2.0"
description = "A CLI to test if semantic-release is configured"
readme = "README.md"
repository = "https://github.com/EricCrosson/is-semantic-release-configured"
homepage = "https://github.com/EricCrosson/is-semantic-release-configured"
keywords = ["cli", "semantic-release"]
categories = ["command-line-utilities"]
exclude = [
  "/.envrc",
  "/.github",
  "/CHANGELOG.md",
  "/flake.{lock,nix}"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "=4.1.1", features = ["cargo", "derive", "wrap_help"] }
env_logger = { version = "=0.10.0", default-features = false }
find-semantic-release-config = "=1.0.3"
serde_json = "=1.0.91"

[profile.release]
lto = true
codegen-units = 1
strip = true
