[package]
name = "is-semantic-release-configured"
version = "1.0.0"
edition = "2021"
authors = ["Eric Crosson <eric.s.crosson@utexas.edu>"]
license = "MIT OR Apache-2.0"
description = "A CLI to test if semantic-release is configured"
readme = "README.md"
homepage = "https://github.com/EricCrosson/is-semantic-release-configured"
keywords = ["cli", "semantic-release"]
categories = ["command-line-utilities"]
exclude = [
  "/.envrc",
  "/.github",
  "/.gitignore",
  "/.releaserc.json",
  "/CHANGELOG.md",
  "/flake.{lock,nix}",
  "/package*.json",
  "/rust-toolchain",
  "/assets"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "=1.0.68"
# clap = { version = "=4.0.32", features = ["cargo", "derive", "wrap_help"] }
serde_json = "=1.0.91"

[profile.release]
lto = true
codegen-units = 1
strip = true
